### ISSUE TITLE
Build instruction

### ISSUE THREAD

**Issue by jjaone** [kpanthagani/COVIDplots#1]
Could you please attach a Readme.md file to this repository and include in it instructions or How-to for us to build such dynamic graphs on our own for other countries of interest, please 😉

Also, would like to know wether this system can be build on Linux and/or opensource environment and w/o a paid license of R-software!

**Comment by kpanthagani** [comment]
Thanks for your comment. R is open source and freely available, so should not be an issue from that end. It is entirely written in R so cannot be run without it. The script wasn't written with the intent of automated customizability for other countries, but it is commented so with some R knowledge it could be adapted. Unfortunately right now I don't have the time to put together automated customizability or user friendly instructions besides what is already included in the script comments.

**Comment by jjaone** [comment]
Thanks, now that I know it is just an R-script with comments I think I can manage  the customization to orher countries. 

In the future, it would be good to have in the script the format of the data it expects so that other data sources for timelines could be used. 

Also, as this is opensource I could do a PR for buold instructions to this repo when I get it running in my Linux system.

Cheers for now,
-jukka (from Finland)
